Repository cornell-zhang/heterocl, pull requests merged in 2020-06, with the labels that each got.

#226 [Pass] Fix Ill-Formed C++ Code in reuse_at
  tvm/src/schedule/schedule_dataflow_rewrite.cc
Labels: Pass

#192 [Backend][Utils] IP Integration Enhancement
  HISTORY
  Makefile
  conda/heterocl/meta.yaml
  hlib/python/hlib/ip/__init__.py
  hlib/python/hlib/ip/byte_swap/__init__.py
  hlib/python/hlib/ip/byte_swap/byte_swap.py
  hlib/python/hlib/ip/byte_swap/lib1/byteswap/my_byteswap_uint.v
  hlib/python/hlib/ip/byte_swap/lib1/c_model.cl
  hlib/python/hlib/ip/byte_swap/lib1/opencl_lib.xml
  hlib/python/hlib/ip/fft.py
  hlib/python/hlib/ip/jpeg_decoder/jpeg.h
  hlib/python/hlib/ip/jpeg_decoder/jpeg_decoder.cl
  hlib/python/hlib/ip/vadd_rtl/__init__.py
  hlib/python/hlib/ip/vadd_rtl/scripts/gen_xo.tcl
  hlib/python/hlib/ip/vadd_rtl/scripts/package_kernel.tcl
  hlib/python/hlib/ip/vadd_rtl/src/hdl/krnl_vadd_rtl.v
  hlib/python/hlib/ip/vadd_rtl/src/hdl/krnl_vadd_rtl_adder.sv
  hlib/python/hlib/ip/vadd_rtl/src/hdl/krnl_vadd_rtl_axi_read_master.sv
  hlib/python/hlib/ip/vadd_rtl/src/hdl/krnl_vadd_rtl_axi_write_master.sv
  hlib/python/hlib/ip/vadd_rtl/src/hdl/krnl_vadd_rtl_control_s_axi.v
  hlib/python/hlib/ip/vadd_rtl/src/hdl/krnl_vadd_rtl_counter.sv
  hlib/python/hlib/ip/vadd_rtl/src/hdl/krnl_vadd_rtl_int.sv
  hlib/python/hlib/ip/vadd_rtl/src/kernel.xml
  hlib/python/hlib/ip/vadd_rtl/vadd_rtl.py
  hlib/python/hlib/op/extern.py
  hlib/python/setup.py
  hlib/tests/test_extern_ip.py
  python/heterocl/report.py
  python/heterocl/schedule.py
  python/heterocl/tvm/module.py
  python/heterocl/tvm/runtime.py
  python/setup.py
  tests/test_codegen_aocl.py
  tests/test_runtime_build.py
  tvm/src/codegen/build_util.cc
  tvm/src/codegen/codegen_c.cc
  tvm/src/codegen/codegen_c.h
  tvm/src/codegen/hlsc/codegen_vhls.cc
  tvm/src/codegen/opencl/codegen_aocl.cc
  tvm/src/codegen/opencl/codegen_aocl.h
  tvm/src/codegen/opencl/codegen_aocl_host.cc
  tvm/src/codegen/opencl/codegen_aocl_host.h
  tvm/src/schedule/schedule_reorder.cc
Labels: Backend, enhancement

#236 [API] Add support for getting bit/slice from expressions
  python/heterocl/tvm/expr.py
  tests/test_dsl_basic.py
Labels: API

#237 [Pass] Remove pass: rewrite_unsafe_select
  python/heterocl/tvm/build_module.py
  tests/test_codegen_vhls.py
Labels: Pass

#238 [Backend][Testing] Fix VHLS codegen for Select; Recover original tests
  tests/test_codegen_vhls.py
  tvm/src/codegen/codegen_c.cc
Labels: Backend, Testing

#229 [API][Backend] Debug Mode for VHLS Runtime
  python/heterocl/devices.py
  python/heterocl/report.py
  python/heterocl/tvm/build_module.py
  python/heterocl/tvm/runtime.py
  tests/test_runtime_build.py
  tvm/src/codegen/build_common.cc
  tvm/src/codegen/build_common.h
  tvm/src/codegen/build_util.cc
  tvm/src/codegen/hlsc/build_hlsc.cc
  tvm/src/codegen/opencl/build_opencl.cc
Labels: API, Backend

#206 [API][Utils] Streaming Support Enhancement v2
  python/heterocl/__init__.py
  python/heterocl/devices.py
  python/heterocl/schedule.py
  python/heterocl/tvm/expr.py
  python/heterocl/tvm/runtime.py
  python/heterocl/tvm/schedule.py
  samples/gemm/gemm_hbm.py
  tests/test_codegen_sdaccel.py
  tests/test_codegen_vhls.py
  tests/test_compute_stencil.py
  tests/test_runtime_build.py
  tests/test_schedule_stream.py
  tvm/HalideIR/src/ir/Expr.h
  tvm/include/tvm/schedule.h
  tvm/src/codegen/build_common.cc
  tvm/src/codegen/build_util.cc
  tvm/src/codegen/codegen_c.cc
  tvm/src/codegen/codegen_c.h
  tvm/src/codegen/hlsc/codegen_hlsc.cc
  tvm/src/codegen/hlsc/codegen_vhls.cc
  tvm/src/codegen/hlsc/codegen_vhls.h
  tvm/src/codegen/opencl/codegen_xocl_host.cc
  tvm/src/pass/lift_allocate_attrs.cc
  tvm/src/pass/stream_inference.cc
  tvm/src/schedule/schedule_dataflow_rewrite.cc
  tvm/src/schedule/schedule_reorder.cc
  tvm/src/template/vitis/Makefile
  tvm/src/template/vitis/config.ini
  tvm/src/template/vitis/config.tcl
Labels: API, Backend

#249 [Backend][SODA] Update tutorial and propagate SODA error
  hlib/python/setup.py
  tests/test_codegen_soda.py
  tutorials/tutorial_09_stencil.py
  tvm/src/codegen/build_soda.cc
Labels: Backend, SODA

#255 [API] Fix reuse_at cannot be used on tensor generated by hcl.compute
  python/heterocl/schedule.py
  tests/issues/test_issue_254.py
  tests/test_schedule_memory.py
Labels: API
