Repository cornell-zhang/heterocl, pull requests merged in 2021-04, with the labels that each got.

#360 [CI] Use decorator=4.4.2 to avoid pkg incompatibility in installation
  python/setup.py
Labels: CI

#361 [Benchmark] Update KNN Digit Recognition and K-Means
  README.md
  docs/compile_flow.png
  docs/lang_overview.png
  samples/digitrec/digitrec_main.py
  samples/digitrec/digitrec_stream.py
  samples/kmeans/kmeans_main.py
Labels: Benchmark

#355 [API][Backend] Introduce external HLS IP module
  .gitignore
  README.md
  hlib/python/hlib/frontend/__init__.py
  hlib/python/hlib/op/extern.py
  python/heterocl/mutator.py
  python/heterocl/tvm/runtime.py
  python/heterocl/tvm/stmt.py
  samples/hls4ml/toynn.py
  tests/test_extern_ip.py
  tvm/HalideIR/src/ir/Expr.h
  tvm/HalideIR/src/ir/IR.cpp
  tvm/HalideIR/src/ir/IR.h
  tvm/HalideIR/src/ir/IREquality.cpp
  tvm/HalideIR/src/ir/IRMutator.cpp
  tvm/HalideIR/src/ir/IRMutator.h
  tvm/HalideIR/src/ir/IRPrinter.cpp
  tvm/HalideIR/src/ir/IRVisitor.cpp
  tvm/HalideIR/src/ir/IRVisitor.h
  tvm/include/tvm/ir.h
  tvm/include/tvm/ir_functor_ext.h
  tvm/include/tvm/ir_mutator.h
  tvm/include/tvm/ir_visitor.h
  tvm/src/api/api_ir.cc
  tvm/src/codegen/codegen_c.cc
  tvm/src/codegen/codegen_c.h
  tvm/src/codegen/hlsc/codegen_vhls.cc
  tvm/src/codegen/hlsc/codegen_vhls.h
  tvm/src/codegen/llvm/codegen_llvm.cc
  tvm/src/codegen/llvm/codegen_llvm.h
  tvm/src/codegen/merlinc/codeanalys_merlinc.cc
  tvm/src/codegen/merlinc/codeanalys_merlinc.h
  tvm/src/lang/ir.cc
  tvm/src/pass/ir_mutator.cc
  tvm/src/pass/ir_visitor.cc
  tvm/src/pass/stream_inference.cc
Labels: API, Backend
