Repository cornell-zhang/heterocl, pull requests merged in 2021-07, with the labels that each got.

#385 [API] Add hcl.assert for Runtime Assertion
  python/heterocl/api.py
  python/heterocl/tvm/stmt.py
  tests/test_api_assert.py
  tests/test_api_assert_cases/basic_assert_tests.py
  tests/test_api_assert_cases/memory_assert_tests.py
  tvm/HalideIR/src/ir/Expr.h
  tvm/HalideIR/src/ir/IR.cpp
  tvm/HalideIR/src/ir/IR.h
  tvm/HalideIR/src/ir/IRMutator.cpp
  tvm/HalideIR/src/ir/IRMutator.h
  tvm/HalideIR/src/ir/IRPrinter.cpp
  tvm/HalideIR/src/ir/IRVisitor.cpp
  tvm/HalideIR/src/ir/IRVisitor.h
  tvm/include/tvm/ir.h
  tvm/include/tvm/ir_functor_ext.h
  tvm/include/tvm/ir_mutator.h
  tvm/include/tvm/ir_visitor.h
  tvm/src/api/api_ir.cc
  tvm/src/codegen/llvm/codegen_llvm.cc
  tvm/src/codegen/llvm/codegen_llvm.h
  tvm/src/lang/ir.cc
  tvm/src/pass/ir_mutator.cc
  tvm/src/pass/ir_visitor.cc
Labels: API

#376 [API] HLS Report Enhancement - Bug Fix
  python/heterocl/report.py
  tests/test_hls_report.py
  tests/test_report_data/expected.json
  tests/test_report_data/sobel_report.xml
  tests/test_report_data/spam_filter_report.xml
Labels: API

#392 [API] Fix hcl.assert for user defined functions
  python/heterocl/api.py
  tests/test_api_assert.py
  tests/test_api_assert_cases/dsl_def_assert_tests.py
  tests/test_api_assert_cases/dsl_def_assert_tests_golden.py
  tvm/src/codegen/llvm/codegen_llvm.cc
  tvm/src/codegen/llvm/codegen_llvm.h
Labels: API

#397 [Docs] Add template for PR
  pull_request_template.md
Labels: Docs

#399 [Pass] Remove Unnecessary Simplification for Bitwise Operators
  tests/issues/test_issue_398.py
  tests/test_api.py
  tvm/HalideIR/src/arithmetic/Simplify.cpp
Labels: Pass
