Repository cornell-zhang/heterocl, pull requests merged in 2021-03, with the labels that each got.

#343 [API] Generate correct error message when operating with NumPy numbers
  python/heterocl/debug.py
  python/heterocl/tensor.py
  python/heterocl/tvm/expr.py
  tests/issues/test_issue_342.py
Labels: API

#337 [API] HLS Report Enhancement
  .circleci/config.yml
  python/heterocl/report.py
  python/setup.py
  tests/test_hls_report.py
  tests/test_report_data/expected.json
  tests/test_report_data/rose-grayscale.jpg
  tests/test_report_data/test_csynth.xml
Labels: API

#330 [API] Add bitcast API
  python/heterocl/compute_api.py
  tests/test_api_bitcast.py
Labels: API

#349 [MLIR] Integrate MLIR into tool flow with a HeteroCL Dialect skeleton
  Makefile
  Makefile.config
  include/hcl/.gitignore
  include/hcl/dialect/HCLIR/HCLIRDialect.h
  include/hcl/dialect/HCLIR/HCLIRDialect.td
  include/hcl/dialect/HCLIR/HCLIROps.h
  include/hcl/dialect/HCLIR/HCLIROps.td
  include/hcl/dialect/Makefile
  pkgs/Makefile.pkg.config
  pkgs/cmake/Makefile
  pkgs/llvm/Makefile
  src/Makefile
  src/hcl/dialect/HCLIR/HCLIRDialect.cc
  src/hcl/dialect/HCLIR/HCLIROps.cc
  src/tvm/codegen/llvm/codegen_cpu.cc
  src/tvm/codegen/llvm/codegen_llvm.cc
  src/tvm/codegen/llvm/codegen_llvm.h
  src/tvm/codegen/llvm/llvm_common.cc
  src/tvm/codegen/llvm/llvm_common.h
  src/tvm/codegen/llvm/llvm_module.cc
Labels: MLIR

#352 [CI] Change mxnet version to 1.7.0
  .circleci/config.yml
Labels: CI
